# Project information
site_name: 'Tributech DataSpace Kit Documentation'
site_description: 'Data audit & sharing technology ensuring trustworthy data'
site_author: 'Tributech Solutions'
docs_dir: docs/

# Copyright
copyright: 'Copyright &copy; 2018 - <script>document.write(new Date().getFullYear())</script> Tributech Solutions GmbH'

# Repo reference
repo_name: 'tributech-solutions/tributech-DSK-docs'
repo_url: 'https://github.com/tributech-solutions/tributech-DSK-docs'

# Navigation
nav:
  - Home: index.md
  - Quick Start:
      - Overview: quickstart/overview.md
      - Install Owner Node: quickstart/install-owner-node.md
      - Create a Dataset: quickstart/create-dataset.md
      - Install DSK IoT Bridge: quickstart/install-bridge.md
      - Setup IoT Device: quickstart/setup-device.md
      - Publish Dataset: quickstart/publish-dataset.md
      - Install Consumer Node: quickstart/install-consumer-node.md
      - Subscribe to Dataset: quickstart/subscribe-dataset.md
  - Introduction:
      - Introduction: introduction/introduction.md
      - Overview: introduction/dsk-overview.md
      - DSK Terminology: introduction/terminology.md
      - DSK Topology: introduction/system-topology.md
  - Setup:
      - Overview: setup/overview.md
      - DSK Node:
          - Setup Options: setup/node/options.md
          - Prerequisites: setup/node/prerequisites.md
          - Setup Steps: setup/node/setup.md
          - Next Steps: setup/node/next-steps.md
      - DSK Agent:
          - Setup Options: setup/agent/options.md
          - Prerequisites: setup/agent/prerequisites.md
          - Setup Agent: setup/agent/setup.md
          - Next Steps: setup/agent/next-steps.md
      - DSK IoT Hub Bridge: setup/iot-hub-bridge/iot-hub-bridge.md
  - Integration:
      - Overview: integration/overview.md
      - DSK Node APIs:
          - Overview: integration/node-api/overview.md
          - Integration Examples: integration/node-api/integration-examples.md
          - API Authentication: integration/node-api/api-authentication.md
          - Next Steps: integration/node-api/next-steps.md
      - Agent Edge Interface:
          - Integration Examples: integration/agent/examples.md
          - Next Steps: integration/agent/next-steps.md

# Configuration
theme:
  name: material
  feature:
    taps: true
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Source Sans Pro'
    code: 'Roboto Mono'
  logo: 'img/icon_white.svg'
  favicon: 'img/favicon.png'
  custom_dir: theme-overrides
  features:
    - navigation.tabs

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/tributech.io/'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/tributechsolutions'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
  #      noclasses: true
  #      pygments_style: monokai
  - toc:
      permalink: true

extra_css:
  - css/customization.css
