# Project information
site_name: 'Tributech DataSpace Kit Documentation'
site_description: 'Data audit & sharing technology ensuring trustworthy data'
site_author: 'Tributech Solutions'
docs_dir: docs/

# Copyright
copyright: 'Copyright &copy; 2018 - <script>document.write(new Date().getFullYear())</script> Tributech Solutions GmbH'

# Repo reference
repo_name: 'tributech-solutions/tributech-DSK-docs'
repo_url: 'https://github.com/tributech-solutions/tributech-DSK-docs'

# Navigation
nav:
  - Home: index.md
  - Quick Start:
      - Overview: quickstart/overview.md
      - Install Owner Node: quickstart/install-owner-node.md
      - Create a Dataset: quickstart/create-dataset.md
      - Install DSK IoT Bridge: quickstart/install-bridge.md
      - Setup IoT Device: quickstart/setup-device.md
      - Publish Dataset: quickstart/publish-dataset.md
      - Install Consumer Node: quickstart/install-consumer-node.md
      - Subscribe to Dataset: quickstart/subscribe-dataset.md
      - Consuming data:
          - Via Dashboards: quickstart/data-consuming/data-via-dashboards.md
          - Via APIs: quickstart/data-consuming/data-via-apis.md
  - Introduction:
      - Product Overview: introduction/product-overview.md
      - Architecture: introduction/architecture.md
      - Auditable data: introduction/auditable-data.md
  - Setup:
      - Overview: setup/overview.md
      - DSK Node:
          - Setup Options: setup/node/setup-options.md
          - Requirements: setup/node/node-requirements.md
          - Setup Guide: setup/node/setup-guide.md
      - DSK Agent:
          - Setup Options: setup/agent/setup-options.md
          - Agent Edge Setup: setup/agent/edge-setup.md
          #- Agent Embedded Guide: setup/agent/ssm-setup.md
      - DSK IoT Hub Bridge: setup/iot-hub-bridge/iot-hub-bridge.md
  - Integration:
      - Overview: integration/overview.md
      - DSK Node:
          - Overview: integration/node/overview.md
          - Integration Examples: integration/node/integration-examples.md
          - Swagger UI Authorization: integration/node/swagger-ui-authorization.md
      - DSK Agent:
          - Agent Edge:
              - Integration: integration/agent/edge/integration.md
              - Configuration: integration/agent/edge/configuration.md
          #- Agent Embedded: integration/agent/ssm.md

# Configuration
theme:
  name: material
  feature:
    taps: true
  font:
    text: 'Lato'
    code: 'Roboto Mono'
  logo: 'img/icon_white.svg'
  favicon: 'img/favicon.png'
  custom_dir: theme-overrides
  features:
    - navigation.tabs

# Customization
extra:
  version:
    provider: mike
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/tributech.io/'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/tributechsolutions'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
  #      noclasses: true
  #      pygments_style: monokai
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - css/customization.css
